BIBTEX = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\bibtex.exe']
BINDIR = 'C:\\Users\\mdohmen\\AppData\\Local\\Temp/bin'
DVIPS = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\dvips.exe']
DVIPSFLAGS = '-Ppdf'
LATEX = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\latex.exe']
LIBDIR = 'C:\\Users\\mdohmen\\AppData\\Local\\Temp/lib'
MAKEGLOSSARIES = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\makeglossaries.exe']
MAKEINDEX = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\makeindex.exe']
PDF2PS = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\pdf2ps.exe']
PDFLATEX = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\pdflatex.exe']
PDFLATEXFLAGS = '-shell-escape'
PREFIX = 'C:\\Users\\mdohmen\\AppData\\Local\\Temp'
PS2PDF = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\ps2pdf.exe']
PYCMD = ['C:\\Anaconda3\\python.exe']
PYTHONPATH = 'S:\\prog-econ\\final_project_topics_Born'
SPHINX_BUILD = ['C:\\Anaconda3\\Scripts\\sphinx-build.exe']
TEX = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\tex.exe']
XELATEX = ['C:\\Program Files (x86)\\MiKTeX 2.9\\miktex\\bin\\xelatex.exe']
