#! python


def build(ctx):

        
    for model in 'gdppc_baseline', 'gdppc_with_covariates', 'ca_with_covariates', 'gdppc_all_year_averages', 'gdppc_time_placebo', 'gdppc_country_placebo':

        ctx(
            features='run_py_script',
            source='plot_sc_graph.py',
            deps=ctx.path_to(ctx, 'OUT_ANALYSIS', "sc_{}.pickle".format(model)),
            target=ctx.path_to(ctx, 'OUT_FIGURES', "sc_graph_{}.pdf".format(model)),
            append=model,
            name='plot_sc_graph_{}'.format(model)
        )
        
        ctx(
            features='run_py_script',
            source='sc_tables.py',
            deps=ctx.path_to(ctx, 'OUT_ANALYSIS', "sc_{}.pickle".format(model)),
            target=[
                ctx.path_to(ctx, 'OUT_TABLES', "weights_{}.tex".format(model)),
                ctx.path_to(ctx, 'OUT_TABLES', "predictors_{}.tex".format(model))
            ],
            append=model,
            name='plot_sc_graph_{}'.format(model)
        )